{% set name = "cwltool" %}
{% set version = "3.0.20200317203547" %}

package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: 7126c4a69a3fc8e50588b96e32f381ac9d0c23d6ae50bd4c7bbc943830962b28

build:
  number: 0
  noarch: python
  entry_points:
    - cwltool=cwltool.main:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - bagit >=1.6.4
    - mypy_extensions
    - prov ==1.5.1
    - psutil
    - python >=3.5
    - rdflib >=4.2.2,<4.3.0
    - requests >=2.6.1
    # Avoid ruamel.yaml >=0.16,<0.16.5 due to builds with broken dependency.
    # ref: https://github.com/conda-forge/ruamel.yaml-feedstock/pull/117
    - ruamel.yaml >=0.12.4,<0.16|0.16.5.*
    - scandir
    - schema-salad >=5.0,<6
    - setuptools
    - shellescape >=3.4.1,<3.5
    - six >=1.9.0
    - typing_extensions
    - coloredlogs
    - pathlib2 >=2.3.2


test:
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help

about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
