appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: uFwdx+yQLOgvVxr9RwWaGVFIfaCDBa/JcjMFgVegjPqyV7bn4ITxYFPSfLAEw05e90+SKrDcBmTGobendOGrDMZi73IYGRDIeXrMI9Sb4g+cJ+MW/db9QOuuW9+G+iTu4pDPDL7EwNZDv3qwWNnW62pyXkUciye9eHTRdyq+F6xCx/zCqzMBzhPtlpjaaRzs3NmKrPTwbJ7kRXenlAyiA7w1xNaMbBfPnrdHzH+BO+XkLMcG9JycCOGkL93cg/vfJXgVY+J+Yt0gWz5NVR13rAG9aVOotZs+BtGitsqItwTfIvNVVt4HAQmdNvw7eKKnwGndLHkLfB1RfJ1FGRSYgqazfb4l56353iWnMUAKfU+VLRccOfWfE0tuXx5OHIG5LvoUSbWjhe2sg0HOgMIU5irKYJ08ZW0bkqa64U7zO+0mvdaYuMfk3cWlFVFD1vf5UoW/Aql/vdKQBXXYzTcmTfIhPrBc7IDtWBtbyfarmykNZTMxeA3sFumECQT0pGc8Dqm9T7aokDxy0a/VNJ6BDE6XClhbWsDm+8nnS8toVVT6wMiO7ueR6RU3xdLS4E1cq5yxnx26F2CtfaWAvchK0O6SXKXmXRVOy6pbZ4PojchdAc3BWrfCX/m4aNQUP34gIdn6ce7KMybjiP9On31ee5nwLGRWM9563/GEbOgz7pk=}
provider:
  win: azure
conda_forge_output_validation: true
